name: dart_model_crafter
description: A creative and intuitive Dart package to craft Dart models effortlessly from JSON or manual input.
version: 1.0.0
repository: https://github.com/ddr137/model_crafter

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
